# -*- coding: utf-8 -*-
"""FBprophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13KSk6-YRslIihKDbktfZpCt7gWFLRp9Z
"""

from fbprophet import Prophet
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt

dataset = pd.read_csv('AXP_stock_details.csv')
dataset.head()

dataset_stock = dataset[["dates",	"open",	"high",	"low",	"close",	"adjusted_close",	"volume",	"ticker"]].copy()
dataset_stock.head()

# mask = (dataset_stock['dates'] > start_date) & (dataset_stock['dates'] <= end_date)

# dataset_stock = dataset_stock.loc[mask]

# dataset_stock

dataset_stock.dtypes

from datetime import datetime

#setting index as date
dataset_stock['dates'] = pd.to_datetime(dataset_stock.dates,format='%Y-%m-%d')
dataset_stock.index = dataset_stock['dates']

#plot
plt.figure(figsize=(16,10))
plt.plot(dataset_stock['close'], label='Close Price history')
plt.ylabel('Close Price $')
plt.xlabel('Dates')

start_date = '2014-01-01'
end_date = '2019-07-10'

mask = (dataset_stock['dates'] > start_date) & (dataset_stock['dates'] <= end_date)

dataset_stock = dataset_stock.loc[mask]

#plot
plt.figure(figsize=(16,8))
plt.plot(dataset_stock['close'], label='Close Price history')
plt.ylabel('Close Price $')
plt.xlabel('Dates')



#creating dataframe with date and the target variable
data = dataset_stock.sort_index(ascending=True, axis=0)
new_data = pd.DataFrame(index=range(0,len(dataset_stock)),columns=['dates', 'close'])

for i in range(0,len(data)):
    new_data['dates'][i] = data['dates'][i]
    new_data['close'][i] = data['close'][i]
new_data.head()

dataset = new_data.rename(columns = {"dates" : 'ds', "close" : 'y'})
dataset.head()

model = Prophet()
model.add_country_holidays(country_name='US')
model.fit(dataset)
future = model.make_future_dataframe(periods = 365)

forecast = model.predict(future)

forecast.tail()

model.plot(forecast)

forecast.head(10)

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(100)

